steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gabon-palm-ai-ml/titanic-model:latest', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gabon-palm-ai-ml/titanic-model:latest']

  # Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', 'titanic-model', '--image', 'gcr.io/gabon-palm-ai-ml/titanic-model:latest', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

  # Store the model and metrics in Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gsutil', 'cp', 'model.pkl', 'gs://mlops-poc-gcp/models/model.pkl']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gsutil', 'cp', 'metrics.json', 'gs://mlops-poc-gcp/models/metrics.json']

images:
  - 'gcr.io/gabon-palm-ai-ml/titanic-model:latest'

options:
  logging: CLOUD_LOGGING_ONLY
